// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject4.WebRecordTestClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class WebRecordTest
    {
        
        /// <summary>
        /// executeautomationdemosite - Use 'executeautomationdemositeParams' to pass parameters into this method.
        /// </summary>
        public void executeautomationdemosite()
        {
            BrowserWindow.Launch(@"http://executeautomation.com/demosite/Login.html");

            #region Variable Declarations
            HtmlEdit uIUserNameEdit = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument.UIUserNameEdit;
            HtmlEdit uIPasswordEdit = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument.UILoginButton;
            HtmlComboBox uITitleIdComboBox = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument1.UITitleIdComboBox;
            HtmlEdit uIInitialEdit = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument1.UIInitialEdit;
            HtmlEdit uIFirstNameEdit = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument1.UIFirstNameEdit;
            HtmlCheckBox uIHindiCheckBox = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument1.UIHindiCheckBox;
            HtmlInputButton uISaveButton = this.UIExecuteAutomationIntWindow.UIExecuteAutomationDocument1.UISaveButton;
            #endregion

            // Type 'pradeep' in 'UserName' text box
            uIUserNameEdit.Text = this.executeautomationdemositeParams.UIUserNameEditText;

            // Type 'pradeep' in 'Password' text box
            uIPasswordEdit.Text = this.executeautomationdemositeParams.UIPasswordEditText;

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(28, 11));

            // Select 'Mr.' in 'TitleId' combo box
            uITitleIdComboBox.SelectedItem = this.executeautomationdemositeParams.UITitleIdComboBoxSelectedItem;

            // Type 'KR' in 'Initial' text box
            uIInitialEdit.Text = this.executeautomationdemositeParams.UIInitialEditText;

            // Type 'kumar' in 'FirstName' text box
            uIFirstNameEdit.Text = this.executeautomationdemositeParams.UIFirstNameEditText;

            // Select 'Hindi' check box
            uIHindiCheckBox.Checked = this.executeautomationdemositeParams.UIHindiCheckBoxChecked;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(25, 11));
        }
        
        #region Properties
        public virtual executeautomationdemositeParams executeautomationdemositeParams
        {
            get
            {
                if ((this.mexecuteautomationdemositeParams == null))
                {
                    this.mexecuteautomationdemositeParams = new executeautomationdemositeParams();
                }
                return this.mexecuteautomationdemositeParams;
            }
        }
        
        public UIExecuteAutomationIntWindow UIExecuteAutomationIntWindow
        {
            get
            {
                if ((this.mUIExecuteAutomationIntWindow == null))
                {
                    this.mUIExecuteAutomationIntWindow = new UIExecuteAutomationIntWindow();
                }
                return this.mUIExecuteAutomationIntWindow;
            }
        }
        #endregion
        
        #region Fields
        private executeautomationdemositeParams mexecuteautomationdemositeParams;
        
        private UIExecuteAutomationIntWindow mUIExecuteAutomationIntWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'executeautomationdemosite'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class executeautomationdemositeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'pradeep' in 'UserName' text box
        /// </summary>
        public string UIUserNameEditText = "pradeep";
        
        /// <summary>
        /// Type 'pradeep' in 'Password' text box
        /// </summary>
        public string UIPasswordEditText = "pradeep";
        
        /// <summary>
        /// Select 'Mr.' in 'TitleId' combo box
        /// </summary>
        public string UITitleIdComboBoxSelectedItem = "Mr.";
        
        /// <summary>
        /// Type 'KR' in 'Initial' text box
        /// </summary>
        public string UIInitialEditText = "KR";
        
        /// <summary>
        /// Type 'kumar' in 'FirstName' text box
        /// </summary>
        public string UIFirstNameEditText = "kumar";
        
        /// <summary>
        /// Select 'Hindi' check box
        /// </summary>
        public bool UIHindiCheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIExecuteAutomationIntWindow : BrowserWindow
    {
        
        public UIExecuteAutomationIntWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Execute Automation";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Execute Automation");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIExecuteAutomationDocument UIExecuteAutomationDocument
        {
            get
            {
                if ((this.mUIExecuteAutomationDocument == null))
                {
                    this.mUIExecuteAutomationDocument = new UIExecuteAutomationDocument(this);
                }
                return this.mUIExecuteAutomationDocument;
            }
        }
        
        public UIExecuteAutomationDocument1 UIExecuteAutomationDocument1
        {
            get
            {
                if ((this.mUIExecuteAutomationDocument1 == null))
                {
                    this.mUIExecuteAutomationDocument1 = new UIExecuteAutomationDocument1(this);
                }
                return this.mUIExecuteAutomationDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIExecuteAutomationDocument mUIExecuteAutomationDocument;
        
        private UIExecuteAutomationDocument1 mUIExecuteAutomationDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIExecuteAutomationDocument : HtmlDocument
    {
        
        public UIExecuteAutomationDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Execute Automation";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/demosite/Login.html";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://executeautomation.com/demosite/Login.html";
            this.WindowTitles.Add("Execute Automation");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUserNameEdit
        {
            get
            {
                if ((this.mUIUserNameEdit == null))
                {
                    this.mUIUserNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" type=\"text\" maxlength=\"1";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUserNameEdit.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUIUserNameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" type=\"text\" maxlength=\"1";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Login";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Login";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Login\" type=\"submit\" value=\"Login\"";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUILoginButton.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUserNameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIExecuteAutomationDocument1 : HtmlDocument
    {
        
        public UIExecuteAutomationDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Execute Automation";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/demosite/index.html";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://executeautomation.com/demosite/index.html?UserName=pradeep&Password=pradee" +
                "p&Login=Login";
            this.WindowTitles.Add("Execute Automation");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UITitleIdComboBox
        {
            get
            {
                if ((this.mUITitleIdComboBox == null))
                {
                    this.mUITitleIdComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUITitleIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "TitleId";
                    this.mUITitleIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "TitleId";
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "3";
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"TitleId\" id=\"TitleId\" data-val-num";
                    this.mUITitleIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUITitleIdComboBox.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUITitleIdComboBox;
            }
        }
        
        public HtmlEdit UIInitialEdit
        {
            get
            {
                if ((this.mUIInitialEdit == null))
                {
                    this.mUIInitialEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIInitialEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Initial";
                    this.mUIInitialEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Initial";
                    this.mUIInitialEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIInitialEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIInitialEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIInitialEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIInitialEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Initial\" id=\"Initial\" style=\"width";
                    this.mUIInitialEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIInitialEdit.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUIInitialEdit;
            }
        }
        
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "FirstName";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "FirstName";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"FirstName\" id=\"FirstName\" style=\"w";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIFirstNameEdit.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }
        
        public HtmlCheckBox UIHindiCheckBox
        {
            get
            {
                if ((this.mUIHindiCheckBox == null))
                {
                    this.mUIHindiCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIHindiCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = null;
                    this.mUIHindiCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "Hindi";
                    this.mUIHindiCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Value] = "hindi";
                    this.mUIHindiCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.LabeledBy] = null;
                    this.mUIHindiCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIHindiCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIHindiCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=\"Hindi\" type=\"checkbox\" value=\"hind";
                    this.mUIHindiCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "7";
                    this.mUIHindiCheckBox.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUIHindiCheckBox;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Save\" type=\"button\" value=\"Save\"";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "8";
                    this.mUISaveButton.WindowTitles.Add("Execute Automation");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUITitleIdComboBox;
        
        private HtmlEdit mUIInitialEdit;
        
        private HtmlEdit mUIFirstNameEdit;
        
        private HtmlCheckBox mUIHindiCheckBox;
        
        private HtmlInputButton mUISaveButton;
        #endregion
    }
}
